language: python
python:
    # - "2.7"
    - "3.4"
    - "3.5"
    - "nightly"

install: pip install -r dev-requirements.txt

sudo: required

services:
    - docker

env:
    MINIO_STORAGE_ENDPOINT: "localhost:9000"
    MINIO_STORAGE_ACCESS_KEY: weak_access_key
    MINIO_STORAGE_SECRET_KEY: weak_secret_key

before_install:
    - docker run -d -p 9000:9000 -e MINIO_ACCESS_KEY=$MINIO_STORAGE_ACCESS_KEY -e MINIO_SECRET_KEY=$MINIO_STORAGE_SECRET_KEY minio/minio /export

script: "./run_tests.sh"
